// Configuration
const CONFIG = {
    API_URL: `${window.location.origin}/api`,
    ADMIN_ID: '1342762796,963424858,755125265', // Replace with bot admin Telegram ID or comma-separated admin IDs
    PRODUCTS_SAMPLE: [
        {
            id: 1,
            name: "Полуниця в шоколаді",
            name_en: "Strawberry Chocolate",
            name_pl: "Truskawka w czekoladzie",
            description: "Смак спілої полуниці з молочним шоколадом",
            description_en: "Ripe strawberry with milk chocolate",
            description_pl: "Dojrzała truskawka z mleczną czekoladą",
            price: 150,
            category: "фрукти",
            flavor_profile: "солодкі", 
            nicotine_free: false,
            image_url: "/images/product1.svg",
            rating: 4.8,
            emoji: "🍓"
        },
        {
            id: 2,
            name: "Мента та евкаліпт",
            name_en: "Mint & Eucalyptus",
            name_pl: "Mięta i eukaliptus",
            description: "Охолоджуюча суміш м'яти та евкаліпту",
            description_en: "Cooling blend of mint and eucalyptus",
            description_pl: "Chłodząca mieszanka mięty i eukaliptusa",
            price: 140,
            category: "холодні",
            flavor_profile: "холодні",
            nicotine_free: false,
            image_url: "/images/product2.svg",
            rating: 4.6,
            emoji: "❄️"
        },
        {
            id: 3,
            name: "Мангове смуззі",
            name_en: "Mango Smoothie",
            name_pl: "Smoothie z mango",
            description: "Тропічна манго з йогуртом",
            description_en: "Tropical mango with yogurt",
            description_pl: "Tropikalny mango z jogurtem",
            price: 160,
            category: "фрукти",
            flavor_profile: "солодкі",
            nicotine_free: false,
            image_url: "/images/product3.svg",
            rating: 4.9,
            emoji: "🥭"
        },
        {
            id: 4,
            name: "Лимон та лайм",
            name_en: "Lemon & Lime",
            name_pl: "Cytryna i limonka",
            description: "Свіжа комбінація цитрусів",
            description_en: "Fresh citrus combination",
            description_pl: "Świeża kombinacja cytrusów",
            price: 130,
            category: "фрукти",
            flavor_profile: "холодні",
            nicotine_free: false,
            image_url: "/images/product4.svg",
            rating: 4.5,
            emoji: "🍋"
        },
        {
            id: 5,
            name: "Чорниця без нікотину",
            name_en: "Blueberry No Nic",
            name_pl: "Jagody bez nikotyny",
            description: "Солодкі чорниці без нікотину",
            description_en: "Sweet blueberries without nicotine",
            description_pl: "Słodkie jagody bez nikotyny",
            price: 145,
            category: "безнікотинові",
            flavor_profile: "солодкі",
            nicotine_free: true,
            image_url: "/images/product5.svg",
            rating: 4.7,
            emoji: "🫐"
        },
        {
            id: 6,
            name: "Ванільний крем",
            name_en: "Vanilla Cream",
            name_pl: "Krem waniliowy",
            description: "Мариве гідне ванільне кремове задоволення",
            description_en: "Rich vanilla cream flavor",
            description_pl: "Bogaty smak kremowego wanilii",
            price: 155,
            category: "десертні",
            flavor_profile: "солодкі",
            nicotine_free: false,
            image_url: "/images/product6.svg",
            rating: 4.8,
            emoji: "🍦"
        },
        {
            id: 7,
            name: "Льодяна груша",
            name_en: "Icy Pear",
            name_pl: "Lodowata gruszka",
            description: "Охолоджена груша з легкою льодистістю",
            description_en: "Cooled pear with icy freshness",
            description_pl: "Chłodzona gruszka ze świeżością lodu",
            price: 148,
            category: "холодні",
            flavor_profile: "холодні",
            nicotine_free: false,
            image_url: "/images/product7.svg",
            rating: 4.6,
            emoji: "🍐"
        },
        {
            id: 8,
            name: "Шоколадна каша",
            name_en: "Chocolate Oatmeal",
            name_pl: "Czekoladowe płatki",
            description: "Комфортний смак шоколаду та вівса",
            description_en: "Comfort chocolate and oatmeal taste",
            description_pl: "Wygodny smak czekolady i owsa",
            price: 165,
            category: "десертні",
            flavor_profile: "солодкі",
            nicotine_free: false,
            image_url: "/images/product8.svg",
            rating: 4.7,
            emoji: "🍫"
        }
    ]
};
